FROM mmh352/m269:23j

USER root
RUN pip install jupyterlab jupyterlab jupyterlab-ou-brand-extension jupyterlab-cell-status-extension jupyterlab_myst jupyterlab-empinken-extension jupyterlab-skip-traceback jupyterlab-git jupyter-archive jupyterlab-spellchecker jupyterlab-templates jupyterlab-language-pack-fr-FR jupyterlab-language-pack-zh-CN jupyter-resource-usage
USER $USER

